Kubernetes 4
vbrednikov/microservices pull request #10
Opened 2018-01-02 14:54 UTC by vbrednikov

Поддержка Helm и GitLab CI. Задание со звездочкой пока не делал из-за недостатка времени. 
Также добавил конфиг для терраформа, который заодно генерирует сертификат для фронтенда и добавляет его в k8s secrets. Прошу засчитать как звездочку для предыдущего д/з :)

Скриншоты гитлаба:
https://www.dropbox.com/s/kc1fnygxmkdxoa4/Screen%20Shot%202018-01-02%20at%205.43.37%20PM.png?dl=0 

https://www.dropbox.com/s/b8dqm3vrf93xz9v/Screen%20Shot%202018-01-02%20at%205.44.16%20PM.png?dl=0

https://www.dropbox.com/s/9rpk2q0mk5we4qf/Screen%20Shot%202018-01-02%20at%205.44.59%20PM.png?dl=0

2018-01-09 12:04 UTC, chromko requested changes
По работе замечаний нет, кроме одного - добавить в values.yaml файл reddit'а значения переменных, чтобы настраивать конкретный деплой целиком с помощью одного лишь файла со значениями, а не менять values.yml у каждого зависимого чарта.

2018-01-09 12:04 UTC, chromko commented on kubernetes/Charts/reddit/values.yaml
> +---
В него разве не нужно было хоть что-то поместить? По-сути сконкатенировать values.yaml зависимостей.

2018-01-15 05:49 UTC, vbrednikov commented on kubernetes/Charts/reddit/values.yaml
> +---
Добавил

2018-01-15 12:04 UTC, chromko commented
Теперь норм

2018-01-15 12:04 UTC, chromko approved these changes

2018-01-16 11:08 UTC, merged